#!/bin/sh
FILES=$(git diff --cached --name-only --diff-filter=ACMR | sed 's| |\\ |g')
[ -z "$FILES" ] && exit 0

# Format the project
./mvnw validate

# Add back the formatted files to staging
echo "$FILES" | xargs git add

exit 0
