version: '3.7'
services:
  auth-service:
    image: ilikeblue/chat-app-auth-service:v0.1
    container_name: auth-test
    ports:
      - "8080:8080"
    env_file:
      - path: ./.env
        required: true
