version: '3.7'
services:
  auth-service:
    image: ilikeblue/chat-app-auth-service:latest
    container_name: auth-test
    ports:
      - "8020:8020"
    env_file:
      - path: ./.env
        required: true
