server:
  port: ${PORT}

management:
  endpoints:
    web:
      exposure:
        include: health,info,beans
  info:
    env:
      enabled: true

info:
  app:
    name: "authentication and authorization service"
    description: "api for chat app's auth"
    version: 1

spring:
  security:
    user:
      name: admin
      password: $2a$12$pLQ8WLGUq5xXAcE52ZHJcuHK.EAypoWFxQ6n.L/.iK4Skcp0El4eO
  output:
    ansi:
      enabled: always # color terminal output
  datasource:
    url: ${DB_DRIVER}/${DB_HOST}:${DB_PORT}/${DB_NAME}?sslmode=require&sslcert=${DB_ROOT_CERT}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none # create-drop if you want to recreate the table script (use none in prod)
      show-sql: false
      database: postgresql
    open-in-view: false # https://stackoverflow.com/questions/30549489/what-is-this-spring-jpa-open-in-view-true-property-in-spring-boot

# Open-api
#
open-api:
  version: v1.0.0
  server:
    url: "http://localhost:${server.port}" # For testing only
    description: prod
springdoc:
  show-actuator: true
  paths-to-match: /actuator/health, /actuator/info, /api/**

# Logging
# The current logger is log4j2
# The default log4j2 config file is resources/log4j2-spring.xml
# You can define attributes here to override the value in config file
#
logging:
  level:
    root: info
    org:
      springframework:
        web: debug
        jdbc: debug
        security: trace
      hibernate:
        SQL: debug
        type:
          descriptor:
            sql:
              BasicBinder: trace

# Lazy initialization
# spring.main.lazy-initialization=true
