logging:
  level:
    org:
      service:
        auth:
          chatappauthservice:
            configurations:
              AppConfiguration: INFO
  path: ${LOG_PATH:/app/logs}

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false