management:
  endpoints:
    web:
      exposure:
        include: health,info,beans
  info:
    env:
      enabled: true

info:
  app:
    name: "authentication and authorization service"
    description: "api for chat app's auth"
    version: 1

spring:
  config:
    import: secrets.yaml
  output:
    ansi:
      enabled: always # color terminal output
  datasource:
    url: ${postgresql.driver}/${postgresql.host}:${postgresql.port}/${postgresql.database}?sslmode=require&sslcert=${postgresql.root-cert}
    username: ${postgresql.user}
    password: ${postgresql.password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none # create-drop if you want to recreate the table script (use none in prod)
      show-sql: false
      database: postgresql
    open-in-view: false # https://stackoverflow.com/questions/30549489/what-is-this-spring-jpa-open-in-view-true-property-in-spring-boot
  profiles:
    active: @spring.profiles.active@

# Logging
# The current logger is log4j2
# The default log4j2 config file is resources/log4j2-spring.xml
# You can define attributes here to override the value in config file
#
logging:
  level:
    root: info
    org:
      springframework:
        web: debug
        jdbc: debug
        security: trace
      hibernate:
        SQL: debug
        type:
          descriptor:
            sql:
              BasicBinder: trace

# Lazy initialization
# spring.main.lazy-initialization=true





