server:
    port: 8080
spring:
  config:
    activate:
      on-profile: dev
open-api:
  version: v1.0.0
  server:
    url: "http://localhost:${server.port}"
    description: dev

# Spring doc
#
springdoc:
  show-actuator: true
