management:
  endpoints:
    web:
      exposure:
        include: health,info,beans
  info:
    env:
      enabled: true

info:
  app:
    name: "authentication and authorization service"
    description: "Huy ngu vl"
    metadata:
      method: "insert_user"

spring:
  config:
    import: secrets.yaml
  security:
    user:
      name: ${application.security.username}
      password: ${application.security.password}
  output:
    ansi:
      enabled: always # color terminal output
  datasource:
    url: ${postgresql.driver}/${postgresql.host}:${postgresql.port}/${postgresql.database}?sslmode=require&sslcert=${postgresql.root-cert}
    username: ${postgresql.user}
    password: ${postgresql.password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
      show-sql: false
      database: postgresql
    open-in-view: false # https://stackoverflow.com/questions/30549489/what-is-this-spring-jpa-open-in-view-true-property-in-spring-boot

# Logging
# The current logger is log4j2
# The default log4j2 config file is resources/log4j2-spring.xml
# You can define attributes here to override the value in config file
#
logging:
  level:
    root: info
    org:
      springframework:
        web: debug
        jdbc: debug
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

# Lazy initialization
# spring.main.lazy-initialization=true
