logging:
  level:
    root: debug
  file:
    name: false

# Open-api
#
open-api:
  version: v1.0.0
  server:
    url: "${PROTOCOL}://${DOMAIN}:${PORT}" # For testing only
springdoc:
  show-actuator: true
  paths-to-match: /actuator/health, /actuator/info, /api/**