apiVersion: v1
kind: Service
metadata: 
  name: auth-service
  namespace: chat-app
  labels:
    app: auth
spec:
  selector:
    app: auth
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
