apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: chat-app-dev
  labels:
    app: auth
spec:
  selector:
    app: auth
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      nodePort: 30007
