apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
  namespace: chat-app-dev
  labels:
    app: auth
spec:
  replicas: 5
  selector:
    matchLabels:
      app: auth
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: auth
    spec:
      restartPolicy: Always
      containers:
        - name: auth
          image: ilikeblue/chat-app-auth-service:v0.2.3
          ports:
            - containerPort: 8080
              protocol: TCP
          envFrom:
            - configMapRef:
                name: auth-configmap
            - secretRef:
                name: auth-secret
          env:
            - name: MY_POD_ID
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
