services:
  user:
    container_name: chat-app-user-service
    image: ilikeblue/chat-app-user-service:dev-latest
    labels:
      - 'custom.project=chat'
      - 'custom.service=user'
    ports:
      - "8600:80"
    environment:
      - DATABASE_URL=postgresql://user_service:user1234@chat-app-db-service:5432/chat-app?sslmode=disable
      - PORT=80
      - API_VERSION=v1
      - LOG_LEVEL=DEBUG
      - LOG_KIND=TEXT
      - ID_GENERATOR_ADDR=chat-app-snowflake-service:80
      - ID_GENERATOR_CERT_DIR=/etc/chat-app/services/snowflake/ssl/certs
      - COST=12
      - CLOUDINARY_URL=not-real-cloudinary-url
    volumes:
      - ../environments/test/user/ssl:/etc/chat-app/services/snowflake/ssl/certs:ro
    networks:
      - chat-app-user-network
      - chat-app-db-network
      - chat-app-id-generator-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/healthcheck"]
      retries: 5
      start_period: 15s
      start_interval: 5s
      interval: 30s
      timeout: 5s
    depends_on:
      - pgdb

  snowflake:
    container_name: chat-app-snowflake-service
    image: ilikeblue/snowflake-uuid:dev-latest
    labels:
      - 'custom.project=chat'
      - 'custom.service=snowflake'
      - 'custom.option=TLS'
    ports:
      - "9000:80"
    environment:
      - WORKER_ID=1
      - CERT_DIR=/etc/certs
    volumes:
      - ../environments/test/snowflake/ssl:/etc/certs:ro 
    networks:
      - chat-app-id-generator-network
    healthcheck:
      test: ["CMD", "/bin/grpc_health_probe", "-addr=:80", "-tls", "-tls-ca-cert=/etc/certs/ca_cert.pem", "-tls-client-cert=/etc/certs/client_cert.pem", "-tls-client-key=/etc/certs/client_key.pem"]
      retries: 5
      start_period: 15s
      start_interval: 5s
      interval: 30s
      timeout: 5s

  pgdb:
    container_name: chat-app-db-service
    image: postgres:13.5
    labels:
      - 'custom.project=chat'
      - 'custom.service=database'
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=testpass123
      - POSTGRES_DB=chat-app
    ports:
      - "6000:5432"
    volumes:
      - chat-app-db-data:/var/lib/postgresql/data
    networks:
      - chat-app-db-network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "admin", "-d", "chat-app"]
      retries: 5
      start_period: 15s
      start_interval: 3s
      interval: 30s
      timeout: 5s


volumes:
  chat-app-db-data:
    external: true
    name: test_chat-app-db-data

networks:
  chat-app-user-network:
    driver: bridge
    name: chat-app-user-network
  chat-app-db-network:
    driver: bridge
    name: chat-app-db-network
  chat-app-id-generator-network:
    driver: bridge
    name: chat-app-id-generator-network
