services:
  user:
    container_name: chat-app-user-service
    image: ilikeblue/chat-app-user-service:dev-latest
    labels:
      - 'custom.project=chat'
      - 'custom.service=user'
    ports:
      - "8600:80"
    environment:
      - DATABASE_URL=postgresql://user_service:user1234@chat-app-db-service:5432/chat-app?sslmode=disable
      - PORT=80
      - LOG_LEVEL=DEBUG
      - LOG_KIND=TEXT
      - ID_GENERATOR_ADDR=chat-app-snowflake-tls-service:80
      - ID_GENERATOR_CERT_DIR=/etc/chat-app/services/snowflake/ssl/certs
      - ID_GENERATOR_EPOCH=1654041600000
      - PASSWORD_HASH_COST=10
      - ENVIRONMENT=test
      - KAFKA_BROKERS=broker-1:19092,broker-2:19092,broker-3:19092
      - MEDIA_SERVICE_URL=http://chat-app-media-service:80
      - CONVERSATION_SERVICE_URL=http://chat-app-conversation-service:80
      - OUTBOX_CHECK_INTERVAL_MS=200
      - MEILISEARCH_URL=http://chat-app-meilisearch-service:7700
      - MEILISEARCH_API_KEY=d709d5b7-064b-4f5d-acd0-b0d415b83e21
    volumes:
      - ../environments/test/user/services/snowflake/ssl/certs:/etc/chat-app/services/snowflake/ssl/certs:ro 
    networks:
      - chat-app-user-network
      - chat-app-db-network
      - chat-app-id-generator-network
      - chat-app-kafka-network
      - chat-app-media-network
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:80/healthcheck | jq -e '.status == \"UP\"' > /dev/null"]
      retries: 3
      start_period: 15s
      start_interval: 3s
      interval: 30s
      timeout: 10s
    depends_on:
      init:
        condition: service_completed_successfully
      pgdb:
        condition: service_healthy # wait for the database to be healthy before starting the user service

  snowflake-tls:
    container_name: chat-app-snowflake-tls-service
    image: ilikeblue/snowflake-uuid:dev-latest
    labels:
      - 'custom.project=chat'
      - 'custom.service=snowflake'
      - 'custom.option=TLS'
    ports:
      - "9000:80"
    environment:
      - WORKER_ID=1
      - CERT_DIR=/etc/certs
      - EPOCH=1654041600000
    volumes:
      - ../environments/test/snowflake/ssl/certs:/etc/certs:ro 
    networks:
      - chat-app-id-generator-network
    healthcheck:
      test: ["CMD", "/bin/grpc_health_probe", "-addr=:80", "-tls", "-tls-ca-cert=/etc/certs/ca_cert.pem", "-tls-client-cert=/etc/certs/client_cert.pem", "-tls-client-key=/etc/certs/client_key.pem"]
      interval: 5s
      timeout: 5s
      retries: 5

  snowflake-non-tls:
    container_name: chat-app-snowflake-non-tls-service
    image: ilikeblue/snowflake-uuid:dev-latest
    labels:
      - 'custom.project=chat'
      - 'custom.service=snowflake'
      - 'custom.option=non-TLS'
    ports:
      - "9001:80"
    networks:
      - chat-app-id-generator-network
    environment:
      - WORKER_ID=2 
      - EPOCH=1654041600000
    healthcheck:
      test: ["CMD", "/bin/grpc_health_probe", "-addr=:80"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    container_name: chat-app-redis-service
    image: redis:8.4.0
    ports:
      - "6379:6379"
    networks:
      - chat-app-redis-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      retries: 3
      start_period: 30s
      start_interval: 5s
      interval: 60s
      timeout: 15s

  pgdb:
    container_name: chat-app-db-service
    image: postgres:13.5
    labels:
      - 'custom.project=chat'
      - 'custom.service=database'
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=testpass123
      - POSTGRES_DB=chat-app
    ports:
      - "6000:5432"
    volumes:
      - chat-app-db-data:/var/lib/postgresql/data
    networks:
      - chat-app-db-network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "admin", "-d", "chat-app"]
      retries: 3
      start_period: 15s
      start_interval: 3s
      interval: 30s
      timeout: 5s

  meilisearch:
    container_name: chat-app-meilisearch-service
    image: getmeili/meilisearch:v1.31.0
    labels:
      - 'custom.project=chat'
      - 'custom.service=search'
    environment:
      - MEILI_ENV=development
      - MEILI_HTTP_ADDR=0.0.0.0:7700
      - MEILI_MASTER_KEY=d709d5b7-064b-4f5d-acd0-b0d415b83e21
      - MEILI_NO_ANALYTICS=true
      - MEILI_LOG_LEVEL=info
    volumes:
      - chat-app-meili-data:/data.ms
    ports:
      - "7700:7700"
    networks:
      - chat-app-search-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:7700/health || exit 1"]
      retries: 3
      start_period: 30s
      interval: 60s
      timeout: 15s

  controller-1:
    image: apache/kafka:latest
    container_name: chat-app-kafka-controller-1
    labels:
      - 'custom.project=chat'
      - 'custom.service=controller'
      - 'custom.option=1'
    environment:
      - KAFKA_NODE_ID=1
      - KAFKA_PROCESS_ROLES=controller
      - KAFKA_LISTENERS=CONTROLLER://:9093
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@chat-app-kafka-controller-1:9093,2@chat-app-kafka-controller-2:9093,3@chat-app-kafka-controller-3:9093
      - KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS=0
    networks:
      - chat-app-kafka-network
    healthcheck:
      test: ["CMD-SHELL", "/opt/kafka/bin/kafka-cluster.sh cluster-id --bootstrap-controller controller-1:9093 || exit 1"]
      retries: 3
      start_period: 15s
      start_interval: 3s
      interval: 30s
      timeout: 5s

  controller-2:
    image: apache/kafka:latest
    container_name: chat-app-kafka-controller-2
    labels:
      - 'custom.project=chat'
      - 'custom.service=controller'
      - 'custom.option=2'
    environment:
      - KAFKA_NODE_ID=2
      - KAFKA_PROCESS_ROLES=controller
      - KAFKA_LISTENERS=CONTROLLER://:9093
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@chat-app-kafka-controller-1:9093,2@chat-app-kafka-controller-2:9093,3@chat-app-kafka-controller-3:9093
      - KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS=0
    networks:
      - chat-app-kafka-network
    healthcheck:
      test: ["CMD-SHELL", "/opt/kafka/bin/kafka-cluster.sh cluster-id --bootstrap-controller controller-2:9093 || exit 1"]
      retries: 3
      start_period: 15s
      start_interval: 3s
      interval: 30s
      timeout: 5s

  controller-3:
    image: apache/kafka:latest
    container_name: chat-app-kafka-controller-3
    labels:
      - 'custom.project=chat'
      - 'custom.service=controller'
      - 'custom.option=3'
    environment:
      - KAFKA_NODE_ID=3
      - KAFKA_PROCESS_ROLES=controller
      - KAFKA_LISTENERS=CONTROLLER://:9093
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@chat-app-kafka-controller-1:9093,2@chat-app-kafka-controller-2:9093,3@chat-app-kafka-controller-3:9093
      - KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS=0
    networks:
      - chat-app-kafka-network
    healthcheck:
      test: ["CMD-SHELL", "/opt/kafka/bin/kafka-cluster.sh cluster-id --bootstrap-controller controller-3:9093 || exit 1"]
      retries: 3
      start_period: 15s
      start_interval: 3s
      interval: 30s
      timeout: 5s

  broker-1:
    image: apache/kafka:latest
    container_name: chat-app-kafka-broker-1
    labels:
      - 'custom.project=chat'
      - 'custom.service=broker'
      - 'custom.option=1'
    environment:
      - KAFKA_NODE_ID=4
      - KAFKA_PROCESS_ROLES=broker
      - KAFKA_LISTENERS=PLAINTEXT://:19092,PLAINTEXT_HOST://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://broker-1:19092,PLAINTEXT_HOST://localhost:29092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@chat-app-kafka-controller-1:9093,2@chat-app-kafka-controller-2:9093,3@chat-app-kafka-controller-3:9093
      - KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS=0
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=false
    ports:
      - 29092:9092
    networks:
      - chat-app-kafka-network
    healthcheck:
      test: ["CMD-SHELL", "/opt/kafka/bin/kafka-cluster.sh cluster-id --bootstrap-server broker-1:19092 || exit 1"]
      retries: 3
      start_period: 15s
      start_interval: 3s
      interval: 30s
      timeout: 5s
    depends_on:
      - controller-1
      - controller-2
      - controller-3

  broker-2:
    image: apache/kafka:latest
    container_name: chat-app-kafka-broker-2
    labels:
      - 'custom.project=chat'
      - 'custom.service=broker'
      - 'custom.option=2'
    environment:
      - KAFKA_NODE_ID=5
      - KAFKA_PROCESS_ROLES=broker
      - KAFKA_LISTENERS=PLAINTEXT://:19092,PLAINTEXT_HOST://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://broker-2:19092,PLAINTEXT_HOST://localhost:39092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@chat-app-kafka-controller-1:9093,2@chat-app-kafka-controller-2:9093,3@chat-app-kafka-controller-3:9093
      - KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS=0
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=false
    ports:
      - 39092:9092
    networks:
      - chat-app-kafka-network
    healthcheck:
      test: ["CMD-SHELL", "/opt/kafka/bin/kafka-cluster.sh cluster-id --bootstrap-server broker-2:19092 || exit 1"]
      retries: 3
      start_period: 15s
      start_interval: 3s
      interval: 30s
      timeout: 5s
    depends_on:
      - controller-1
      - controller-2
      - controller-3

  broker-3:
    image: apache/kafka:latest
    container_name: chat-app-kafka-broker-3
    labels:
      - 'custom.project=chat'
      - 'custom.service=broker'
      - 'custom.option=3'
    environment:
      - KAFKA_NODE_ID=6
      - KAFKA_PROCESS_ROLES=broker
      - KAFKA_LISTENERS=PLAINTEXT://:19092,PLAINTEXT_HOST://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://broker-2:19092,PLAINTEXT_HOST://localhost:49092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@chat-app-kafka-controller-1:9093,2@chat-app-kafka-controller-2:9093,3@chat-app-kafka-controller-3:9093
      - KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS=0
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=false
    ports:
      - 49092:9092
    networks:
      - chat-app-kafka-network
    healthcheck:
      test: ["CMD-SHELL", "/opt/kafka/bin/kafka-cluster.sh cluster-id --bootstrap-server broker-3:19092 || exit 1"]
      retries: 3
      start_period: 15s
      start_interval: 3s
      interval: 30s
      timeout: 5s
    depends_on:
      - controller-1
      - controller-2
      - controller-3

  init:
    image: ilikeblue/chat-app-init-service:latest
    container_name: chat-app-init-service
    labels:
      - 'custom.project=chat'
      - 'custom.service=init'
    environment:
      - APP_ENVIRONMENT=development
      - KAFKA_ENABLED=true
      - KAFKA_BROKERS=broker-1:19092,broker-2:19092,broker-3:19092
      - KAFKA_TOPICS=participant-resource-update:3:3,participant-resource-update-dlq:2:2,message-resource-created:3:3,event-resource-created:3:3,asset-resource-confirm:3:3,asset-resource-delete:3:3,asset-resource-delete-dlq:2:2,inbox-resource-created:3:3,conversation-event-resource-created:3:3,user-resource-updated:3:3
      - MEILISEARCH_ENABLED=true
      - MEILISEARCH_HOST=http://chat-app-meilisearch-service:7700
      - MEILISEARCH_API_KEY=d709d5b7-064b-4f5d-acd0-b0d415b83e21
      - MINIO_ENABLED=false
    networks:
      - chat-app-kafka-network
      - chat-app-search-network
    depends_on:
      broker-1:
        condition: service_healthy
      broker-2:
        condition: service_healthy
      broker-3:
        condition: service_healthy
      meilisearch:
        condition: service_healthy

volumes:
  chat-app-db-data:
    external: true
    name: test_chat-app-db-data
  chat-app-meili-data:
    external: true
    name: test_chat-app-meili-data

networks:
  chat-app-search-network:
    driver: bridge
    name: chat-app-search-network
  chat-app-redis-network:
    driver: bridge
    name: chat-app-redis-network
  chat-app-user-network:
    driver: bridge
    name: chat-app-user-network
  chat-app-db-network:
    driver: bridge
    name: chat-app-db-network
  chat-app-id-generator-network:
    driver: bridge
    name: chat-app-id-generator-network
  chat-app-kafka-network:
    driver: bridge
    name: chat-app-kafka-network
  chat-app-media-network:
    driver: bridge
    name: chat-app-media-network
