services:
  auth:
    container_name: chat-app-auth-service
    image: ilikeblue/chat-app-auth-service:dev-latest
    labels:
      - 'custom.project=chat'
      - 'custom.service=auth'
    ports:
      - "8400:80"
    env_file:
      - ../environments/dev/.env.auth
    networks:
      - chat-app-user-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/healthcheck"]
      start_interval: 10s # wait for 10s before starting healthcheck
      interval: 30s # check every 30s
      timeout: 5s # timeout after 5s
      retries: 5 # retry 5 times

  user:
    container_name: chat-app-user-service
    image: ilikeblue/chat-app-user-service:dev-latest
    labels:
      - 'custom.project=chat'
      - 'custom.service=user'
    ports:
      - "8600:80"
    env_file:
      - ../environments/dev/.env.user
    volumes:
      - ../environments/dev/user/ssl:/etc/snowflake/ssl/certs:ro
    networks:
      - chat-app-user-network
      - chat-app-db-network
      - chat-app-id-generator-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/healthcheck"]
      start_interval: 10s # wait for 10s before starting healthcheck
      interval: 30s # check every 30s
      timeout: 5s # timeout after 5s
      retries: 5 # retry 5 times
    depends_on:
      - pgdb

  snowflake:
    container_name: chat-app-snowflake-service
    image: ilikeblue/snowflake-uuid:dev-latest
    labels:
      - 'custom.project=chat'
      - 'custom.service=snowflake'
      - 'custom.option=TLS'
    ports:
      - "9000:80"
    env_file:
      - ../environments/dev/.env.snowflake
    volumes:
      - ../environments/dev/snowflake/ssl:/etc/certs:ro 
    networks:
      - chat-app-id-generator-network
    healthcheck:
      test: ["CMD", "/bin/grpc_health_probe", "-addr=:80", "-tls", "-tls-ca-cert=/etc/certs/ca_cert.pem", "-tls-client-cert=/etc/certs/client_cert.pem", "-tls-client-key=/etc/certs/client_key.pem"]
      interval: 5s
      timeout: 5s
      retries: 5

  pgdb:
    container_name: chat-app-db-service
    image: postgres:13.5
    labels:
      - 'custom.project=chat'
      - 'custom.service=database'
    env_file:
      - ../environments/dev/.env.pgdb
    ports:
      - "6000:5432"
    volumes:
      - chat-app-db-data:/var/lib/postgresql/data
    networks:
      - chat-app-db-network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "admin", "-d", "chat-app"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  chat-app-db-data:
    external: true
    name: test_chat-app-db-data

networks:
  chat-app-user-network:
    driver: bridge
    name: chat-app-user-network
  chat-app-db-network:
    driver: bridge
    name: chat-app-db-network
  chat-app-id-generator-network:
    driver: bridge
    name: chat-app-id-generator-network
