services:
  user:
    container_name: chat-app-user-service
    image: ilikeblue/chat-app-user-service:dev-latest
    labels:
      - 'custom.project=chat'
      - 'custom.service=user'
    ports:
      - "8600:80"
    environment:
      - DATABASE_URL=postgresql://user_service:user1234@chat-app-db-service:5432/chat-app?sslmode=disable
      - PORT=80
      - API_VERSION=v1
      - LOG_LEVEL=DEBUG
      - LOG_KIND=TEXT
      - ID_GENERATOR_ADDR=chat-app-snowflake-service:80
      - ID_GENERATOR_CERT_DIR=/etc/chat-app/services/snowflake/ssl/certs
      - COST=12
      - CLOUDINARY_URL=not-real-cloudinary-url
      - KAFKA_BROKERS=broker-1:19092
    volumes:
      - ../environments/test/user/ssl:/etc/chat-app/services/snowflake/ssl/certs:ro
    networks:
      - chat-app-user-network
      - chat-app-db-network
      - chat-app-id-generator-network
      - chat-app-kafka-network
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:80/healthcheck | jq -e '.status == \"UP\"' > /dev/null"]
      retries: 3
      start_period: 15s
      start_interval: 3s
      interval: 30s
      timeout: 5s
    depends_on:
      pgdb:
        condition: service_healthy # wait for the database to be healthy before starting the user service

  snowflake:
    container_name: chat-app-snowflake-service
    image: ilikeblue/snowflake-uuid:dev-latest
    labels:
      - 'custom.project=chat'
      - 'custom.service=snowflake'
      - 'custom.option=TLS'
    ports:
      - "9000:80"
    environment:
      - WORKER_ID=1
      - CERT_DIR=/etc/certs
    volumes:
      - ../environments/test/snowflake/ssl:/etc/certs:ro 
    networks:
      - chat-app-id-generator-network
    healthcheck:
      test: ["CMD", "/bin/grpc_health_probe", "-addr=:80", "-tls", "-tls-ca-cert=/etc/certs/ca_cert.pem", "-tls-client-cert=/etc/certs/client_cert.pem", "-tls-client-key=/etc/certs/client_key.pem"]
      retries: 3
      start_period: 15s
      start_interval: 3s
      interval: 30s
      timeout: 5s

  pgdb:
    container_name: chat-app-db-service
    image: postgres:13.5
    labels:
      - 'custom.project=chat'
      - 'custom.service=database'
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=testpass123
      - POSTGRES_DB=chat-app
    ports:
      - "6000:5432"
    volumes:
      - chat-app-db-data:/var/lib/postgresql/data
    networks:
      - chat-app-db-network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "admin", "-d", "chat-app"]
      retries: 3
      start_period: 15s
      start_interval: 3s
      interval: 30s
      timeout: 5s

  controller-1:
    image: apache/kafka:latest
    container_name: chat-app-kafka-controller-1
    labels:
      - 'custom.project=chat'
      - 'custom.service=controller'
      - 'custom.option=1'
    environment:
      - KAFKA_NODE_ID=1
      - KAFKA_PROCESS_ROLES=controller
      - KAFKA_LISTENERS=CONTROLLER://:9093
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@chat-app-kafka-controller-1:9093
      - KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS=0
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=false
    networks:
      - chat-app-kafka-network
    healthcheck:
      test: ["CMD-SHELL", "/opt/kafka/bin/kafka-cluster.sh cluster-id --bootstrap-controller controller-1:9093 || exit 1"]
      retries: 3
      start_period: 15s
      start_interval: 3s
      interval: 30s
      timeout: 5s

  broker-1:
    image: apache/kafka:latest
    container_name: chat-app-kafka-broker-1
    labels:
      - 'custom.project=chat'
      - 'custom.service=broker'
      - 'custom.option=1'
    environment:
      - KAFKA_NODE_ID=4
      - KAFKA_PROCESS_ROLES=broker
      - KAFKA_LISTENERS='PLAINTEXT://:19092,PLAINTEXT_HOST://:9092'
      - KAFKA_ADVERTISED_LISTENERS='PLAINTEXT://broker-1:19092,PLAINTEXT_HOST://localhost:29092'
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@chat-app-kafka-controller-1:9093
      - KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS=0
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=false
    ports:
      - 29092:9092
    networks:
      - chat-app-kafka-network
      - chat-app-user-network
    healthcheck:
      test: ["CMD-SHELL", "/opt/kafka/bin/kafka-cluster.sh cluster-id --bootstrap-server broker-1:19092 || exit 1"]
      retries: 3
      start_period: 15s
      start_interval: 3s
      interval: 30s
      timeout: 5s
    depends_on:
      - controller-1


volumes:
  chat-app-db-data:
    external: true
    name: test_chat-app-db-data

networks:
  chat-app-user-network:
    driver: bridge
    name: chat-app-user-network
  chat-app-db-network:
    driver: bridge
    name: chat-app-db-network
  chat-app-id-generator-network:
    driver: bridge
    name: chat-app-id-generator-network
  chat-app-kafka-network:
    driver: bridge
    name: chat-app-kafka-network
