package constants

const (
	INVALID_DEVICE           = "INVALID_DEVICE"
	REFRESH_TOKEN_REUSE      = "REFRESH_TOKEN_REUSE"
	INVALID_PASSWORD         = "INVALID_PASSWORD"
	REFRESH_TOKEN_NOT_FOUND  = "REFRESH_TOKEN_NOT_FOUND"
	SESSION_REVOKED_BY_OWNER = "SESSION_REVOKED_BY_OWNER"
)
